---
version: '2'
services:
  web:
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: 'development'
  rabbitmq:
    environment:
      # Development password.
      RABBITMQ_DEFAULT_PASS: 'dosomething'
